<?php

namespace PhSpring\Generator;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-24 at 14:36:55.
 */
class ProxyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Proxy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Proxy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PhSpring\Generator\Proxy::setNamespace
     * @todo   Implement testSetNamespace().
     */
    public function testSetNamespace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Generator\Proxy::generate
     * @todo   Implement testGenerate().
     */
    public function testGenerate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
