<?php

namespace PhSpring\Service;

use PHPUnit_Framework_TestCase;
use PhSpring\TestFixtures\Service\ComponentFixture;
use PhSpring\TestFixtures\Service\ComponentInterface;
use PhSpring\TestFixtures\Service\FirstImplementationOfInterface;
use PhSpring\TestFixtures\Service\LazyComponent;
use PhSpring\TestFixtures\Service\LazyPrototypeComponent;
use PhSpring\TestFixtures\Service\PrototypeComponentFixture;
use PhSpring\TestFixtures\Service\SecondImplementationOfInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-24 at 14:36:55.
 */
class HelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Helper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @test
     */
    public function doNothing(){
        $this->assertTrue(true);
    }


}
