<?php

namespace PhSpring\Engine\Handler;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 07:49:52.
 */
class ConfigHandlerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ConfigHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConfigHandler;
    }

    /**
     * @covers PhSpring\Engine\Handler\ConfigHandler::run
     * @test
     * 
     */
    public function testRun() {
    }

}
