<?php

namespace PhSpring\Annotations;

use PHPUnit_Framework_TestCase;
use PhSpring\Service\Helper;
use PhSpring\TestFixtures\Form\SimpleForm;
use Symfony\Component\Validator\ValidatorBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-27 at 11:37:26.
 */
class ValidTest extends PHPUnit_Framework_TestCase {

    /**
     * @test
     */
    public function simpleForm() {
        Helper::addServiceClass(SimpleForm::class);
        $form = Helper::getService(SimpleForm::class);
        
        $builder = new ValidatorBuilder();
        $builder->enableAnnotationMapping();
        $validator = $builder->getValidator();
        $response = $validator->validate($form);
        $this->assertEquals(5, count($response));
    }

}
