<?php

namespace PhSpring\Engine;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-24 at 14:37:03.
 */
class ClassInvokerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ClassInvoker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ClassInvoker;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PhSpring\Engine\ClassInvoker::getNewInstanceByRefl
     * @todo   Implement testGetNewInstanceByRefl().
     */
    public function testGetNewInstanceByRefl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Engine\ClassInvoker::getNewInstance
     * @todo   Implement testGetNewInstance().
     */
    public function testGetNewInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
