<?php

namespace PhSpring\Engine;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-24 at 14:37:02.
 */
class InvokerConfigTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var InvokerConfig
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new InvokerConfig;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PhSpring\Engine\InvokerConfig::getMethodBeforeHandlers
     * @todo   Implement testGetMethodBeforeHandlers().
     */
    public function testGetMethodBeforeHandlers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Engine\InvokerConfig::getRequestHelper
     * @todo   Implement testGetRequestHelper().
     */
    public function testGetRequestHelper() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Engine\InvokerConfig::setRequestHelper
     * @todo   Implement testSetRequestHelper().
     */
    public function testSetRequestHelper() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
