<?php

namespace PhSpring\Annotation;

use PhSpring\Annotations\Autowired;
use PhSpring\TestFixtures\Collection as CollectionFixture;
use PhSpring\TestFixtures\Singleton;
use ReflectionProperty;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-27 at 10:55:28.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Collection
     */
    protected $collection;

    /**
     *
     * @var ReflectionProperty
     */
    private $property;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->property = new ReflectionProperty(CollectionFixture::class, 'arrayObject');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PhSpring\Annotation\Collection::run
     * @todo   Implement testRun().
     */
    public function testRunWithoutAnnotations() {
        $this->setEnv();
        $this->assertTrue($this->property->getValue($this->fixture) === null);
        $this->collection->run($this->fixture);
        $this->assertTrue($this->property->getValue($this->fixture) === null);
    }

    /**
     * @covers PhSpring\Annotation\Collection::run
     * @todo   Implement testRun().
     */
    public function testRunWithAnnotations() {
        $this->setEnv(array(new Autowired(array())));
        $this->assertTrue($this->property->getValue($this->fixture) === null);
        $this->collection->run($this->fixture);
        $this->assertTrue($this->property->getValue($this->fixture) === Singleton::getInstance());
    }

    private function setEnv(array $annotations = array()) {
        $this->property = new ReflectionProperty(CollectionFixture::class, 'arrayObject');
        $this->property->setAccessible(true);
        
        $this->collection = new Collection($annotations, $this->property);
        $this->fixture = new CollectionFixture();
    }

}
