<?php

namespace PhSpring\Annotation;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-24 at 14:36:47.
 */
class HelperTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Helper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Helper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PhSpring\Annotation\Helper::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::getPropertyType
     * @todo   Implement testGetPropertyType().
     */
    public function testGetPropertyType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::getAnnotationHandler
     * @todo   Implement testGetAnnotationHandler().
     */
    public function testGetAnnotationHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::getClassAnnotations
     * @todo   Implement testGetClassAnnotations().
     */
    public function testGetClassAnnotations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::getPropertyAnnotations
     * @todo   Implement testGetPropertyAnnotations().
     */
    public function testGetPropertyAnnotations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::getMethodAnnotations
     * @todo   Implement testGetMethodAnnotations().
     */
    public function testGetMethodAnnotations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::hasAnnotation
     * @todo   Implement testHasAnnotation().
     */
    public function testHasAnnotation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::getClassAnnotation
     * @todo   Implement testGetClassAnnotation().
     */
    public function testGetClassAnnotation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::getMethodAnnotation
     * @todo   Implement testGetMethodAnnotation().
     */
    public function testGetMethodAnnotation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PhSpring\Annotation\Helper::getPropertyAnnotation
     * @todo   Implement testGetPropertyAnnotation().
     */
    public function testGetPropertyAnnotation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
